PENDING = "PENDING"
UNDER_REVIEW = "UNDER_REVIEW"
APPROVED = "APPROVED"
WAITING_FOR_PAYMENT = "WAITING_FOR_PAYMENT"
PAID = "PAID"
CONFIRMED = "CONFIRMED"
READY_FOR_TRAVEL = "READY_FOR_TRAVEL"
IN_PROGRESS = "IN_PROGRESS"
COMPLETED = "COMPLETED"


RESERVATION_STATUSES = (
    PENDING,
    UNDER_REVIEW,
    APPROVED,
    WAITING_FOR_PAYMENT,
    PAID,
    CONFIRMED,
    READY_FOR_TRAVEL,
    IN_PROGRESS,
    COMPLETED,
)

VALID_TRANSITIONS = {
    PENDING: frozenset({UNDER_REVIEW}),
    UNDER_REVIEW: frozenset({APPROVED}),
    APPROVED: frozenset({WAITING_FOR_PAYMENT}),
    WAITING_FOR_PAYMENT: frozenset({PAID}),
    PAID: frozenset({CONFIRMED}),
    CONFIRMED: frozenset({READY_FOR_TRAVEL}),
    READY_FOR_TRAVEL: frozenset({IN_PROGRESS}),
    IN_PROGRESS: frozenset({COMPLETED}),
    COMPLETED: frozenset(),
}
